package com.joedobo27.rs;

public enum Creature {
    NONE("none"),
    HUMAN("human"),
    SALESMAN("salesman"),
    BROWN_COW("brown cow"),
    GUARDTOUGH("guardtough"),
    GUARDBRUTAL("guardbrutal"),
    BLACK_WOLF("black wolf"),
    TROLL("troll"),
    BROWN_BEAR("brown bear"),
    BLACK_BEAR("black bear"),
    LARGE_RAT("large rat"),
    CAVE_BUG("cave bug"),
    MOUNTAIN_LION("mountain lion"),
    WILD_CAT("wild cat"),
    JOE_THE_STUPE("joe the stupe"),
    RED_DRAGON("red dragon"),
    GREEN_DRAGON_HATCHLING("green dragon hatchling"),
    BLACK_DRAGON_HATCHLING("black dragon hatchling"),
    WHITE_DRAGON_HATCHLING("white dragon hatchling"),
    FOREST_GIANT("forest giant"),
    UNICORN("unicorn"),
    KYKLOPS("kyklops"),
    GOBLIN("goblin"),
    HUGE_SPIDER("huge spider"),
    LAVA_SPIDER("lava spider"),
    GOBLIN_LEADER("goblin leader"),
    TROLL_KING("troll king"),
    SPIRIT_GUARD("spirit guard"),
    SPIRIT_SENTRY("spirit sentry"),
    SPIRIT_AVENGER("spirit avenger"),
    SPIRIT_BRUTE("spirit brute"),
    SPIRIT_TEMPLAR("spirit templar"),
    SPIRIT_SHADOW("spirit shadow"),
    JENN_KELLON_TOWER_GUARD("jenn-kellon tower guard"),
    HORDE_OF_THE_SUMMONED_TOWER_GUARD("horde of the summoned tower guard"),
    MOL_REHAN_TOWER_GUARD("mol-rehan tower guard"),
    ISLES_TOWER_GUARD("isles tower guard"),
    BARTENDER("bartender"),
    SANTA_CLAUS("santa claus"),
    EVIL_SANTA("evil santa"),
    WILD_BOAR("wild boar"),
    MOUNTAIN_GORILLA("mountain gorilla"),
    ANACONDA("anaconda"),
    RABID_HYENA("rabid hyena"),
    PIG("pig"),
    HEN("hen"),
    ROOSTER("rooster"),
    CHICKEN("chicken"),
    DOG("dog"),
    CALF("calf"),
    BULL("bull"),
    BISON("bison"),
    HORSE("horse"),
    FOAL("foal"),
    EASTER_BUNNY("easter bunny"),
    DEER("deer"),
    PHEASANT("pheasant"),
    LAVA_FIEND("lava fiend"),
    CROCODILE("crocodile"),
    SCORPION("scorpion"),
    TORMENTOR("tormentor"),
    GUIDE("guide"),
    LADY_OF_THE_LAKE("lady of the lake"),
    COBRA_KING("cobra king"),
    CHILD("child"),
    AVENGER_OF_THE_LIGHT("avenger of the light"),
    ZOMBIE("zombie"),
    SEA_SERPENT("sea serpent"),
    HUGE_SHARK("huge shark"),
    SOL_DEMON("sol demon"),
    DEATHCRAWLER_MINION("deathcrawler minion"),
    SPAWN_OF_UTTACHA("spawn of uttacha"),
    SON_OF_NOGUMP("son of nogump"),
    DRAKESPIRIT("drakespirit"),
    EAGLESPIRIT("eaglespirit"),
    EPIPHANY_OF_VYNORA("epiphany of vynora"),
    JUGGERNAUT_OF_MAGRANON("juggernaut of magranon"),
    MANIFESTATION_OF_FO("manifestation of fo"),
    INCARNATION_OF_LIBILA("incarnation of libila"),
    HELL_HORSE("hell horse"),
    HELL_HOUND("hell hound"),
    HELL_SCORPIOUS("hell scorpious"),
    WORG("worg"),
    SKELETON("skeleton"),
    WRAITH("wraith"),
    SEAL("seal"),
    TORTOISE("tortoise"),
    CRAB("crab"),
    SHEEP("sheep"),
    BLUE_WHALE("blue whale"),
    SEAL_CUB("seal cub"),
    DOLPHIN("dolphin"),
    OCTOPUS("octopus"),
    LAMB("lamb"),
    RAM("ram"),
    BLACK_DRAGON("black dragon"),
    BLUE_DRAGON("blue dragon"),
    GREEN_DRAGON("green dragon"),
    WHITE_DRAGON("white dragon"),
    BLUE_DRAGON_HATCHLING("blue dragon hatchling"),
    RED_DRAGON_HATCHLING("red dragon hatchling"),
    FOG_SPIDER("fog spider"),
    RIFT_BEAST("rift beast"),
    RIFT_JACKAL("rift jackal"),
    RIFT_OGRE("rift ogre"),
    RIFT_WARMASTER("rift warmaster"),
    RIFT_OGRE_MAGE("rift ogre mage"),
    RIFT_CASTER("rift caster"),
    RIFT_SUMMONER("rift summoner"),
    NPC_HUMAN("npc human");

    private final String name;

    Creature(String name) {
        this.name = name;
    }
}
