package com.joedobo27.rs;

import java.util.Arrays;
import java.util.Objects;

public enum Creature {
    NONE,
    HUMAN,
    SALESMAN,
    BROWN_COW,
    GUARDTOUGH,
    GUARDBRUTAL,
    BLACK_WOLF,
    TROLL,
    BROWN_BEAR,
    BLACK_BEAR,
    LARGE_RAT,
    CAVE_BUG,
    MOUNTAIN_LION,
    WILD_CAT,
    JOE_THE_STUPE,
    RED_DRAGON,
    GREEN_DRAGON_HATCHLING,
    BLACK_DRAGON_HATCHLING,
    WHITE_DRAGON_HATCHLING,
    FOREST_GIANT,
    UNICORN,
    KYKLOPS,
    GOBLIN,
    HUGE_SPIDER,
    LAVA_SPIDER,
    GOBLIN_LEADER,
    TROLL_KING,
    SPIRIT_GUARD,
    SPIRIT_SENTRY,
    SPIRIT_AVENGER,
    SPIRIT_BRUTE,
    SPIRIT_TEMPLAR,
    SPIRIT_SHADOW,
    JENN0KELLON_TOWER_GUARD,
    HORDE_OF_THE_SUMMONED_TOWER_GUARD,
    MOL0REHAN_TOWER_GUARD,
    ISLES_TOWER_GUARD,
    BARTENDER,
    SANTA_CLAUS,
    EVIL_SANTA,
    WILD_BOAR,
    MOUNTAIN_GORILLA,
    ANACONDA,
    RABID_HYENA,
    PIG,
    HEN,
    ROOSTER,
    CHICKEN,
    DOG,
    CALF,
    BULL,
    BISON,
    HORSE,
    FOAL,
    EASTER_BUNNY,
    DEER,
    PHEASANT,
    LAVA_FIEND,
    CROCODILE,
    SCORPION,
    TORMENTOR,
    GUIDE,
    LADY_OF_THE_LAKE,
    COBRA_KING,
    CHILD,
    AVENGER_OF_THE_LIGHT,
    ZOMBIE,
    SEA_SERPENT,
    HUGE_SHARK,
    SOL_DEMON,
    DEATHCRAWLER_MINION,
    SPAWN_OF_UTTACHA,
    SON_OF_NOGUMP,
    DRAKESPIRIT,
    EAGLESPIRIT,
    EPIPHANY_OF_VYNORA,
    JUGGERNAUT_OF_MAGRANON,
    MANIFESTATION_OF_FO,
    INCARNATION_OF_LIBILA,
    HELL_HORSE,
    HELL_HOUND,
    HELL_SCORPIOUS,
    WORG,
    SKELETON,
    WRAITH,
    SEAL,
    TORTOISE,
    CRAB,
    SHEEP,
    BLUE_WHALE,
    SEAL_CUB,
    DOLPHIN,
    OCTOPUS,
    LAMB,
    RAM,
    BLACK_DRAGON,
    BLUE_DRAGON,
    GREEN_DRAGON,
    WHITE_DRAGON,
    BLUE_DRAGON_HATCHLING,
    RED_DRAGON_HATCHLING,
    FOG_SPIDER,
    RIFT_BEAST,
    RIFT_JACKAL,
    RIFT_OGRE,
    RIFT_WARMASTER,
    RIFT_OGRE_MAGE,
    RIFT_CASTER,
    RIFT_SUMMONER,
    NPC_HUMAN;


    static Creature getCreatureFromName(String name) {
        return Arrays.stream(values())
                .filter(creature -> Objects.equals(name, creature.getName()))
                .findFirst()
                .orElseThrow(RuntimeException::new);
    }
    String getName() {
        return this.name().toLowerCase().replace("_", " ").replace("0", "-");
    }

}
